Repository gfroidcourt/iut-onboarding, pull requests merged in 2021-12, with the labels that each got.

#18 Loading transition
  package-lock.json
  src/App.vue
  src/assets/linepath.svg
  src/assets/logo.png
  src/assets/logo_iut.svg
  src/components/LoadingOverlay.vue
  src/stylesheets/reset.css
Labels: UI, Component

#22 Animated background
  .eslintrc.js
  src/App.vue
  src/assets/path1.svg
  src/assets/path2.svg
  src/assets/path3.svg
  src/assets/path4.svg
  src/assets/snow1.svg
  src/assets/snow2.svg
  src/assets/snow3.svg
  src/assets/wave1.svg
  src/assets/wave2.svg
  src/assets/wave3.svg
  src/assets/wave4.svg
  src/components/Background.vue
Labels: UI, Component

#28 Récupération des menus CROUS
  package-lock.json
  package.json
  src/App.vue
  src/scrapMeal.js
Labels: API

#29 Carte menu crous
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/components/MenuCard.vue
  src/scrapMeal.js
Labels: Component
