Repository gfroidcourt/iut-onboarding, pull requests merged in 2022-03, with the labels that each got.

#57 Hot fix for production
  src/App.vue
  src/components/DateHourHeader.vue
  src/components/PlanningCard.vue
  src/components/WeatherCard.vue
  src/views/NextPlannings.vue
  src/views/TransportWeather.vue
Labels: bug, Frontend

#65 Refresh des données régulièrement
  src/components/WeatherCard.vue
  src/views/NextPlannings.vue
Labels: Frontend

#63 Loading bar
  src/App.vue
  src/components/LoadingBar.vue
Labels: UI, Component, Frontend

#69 Fix #56 planning entre 11h30 et 13h30
  src/views/NextPlannings.vue
Labels: bug

#74 Plannings font size
  src/App.vue
  src/components/PlanningCard.vue
Labels: Frontend

#72 Scrap identifiants ICal Hyperplanning
  CONTRIBUTING.md
  package.json
  src/icals.json
  src/views/NextPlannings.vue
  tools/package.json
  tools/updateIcals.js
Labels: Frontend
