Repository gfroidcourt/iut-onboarding, pull requests merged in 2022-01, with the labels that each got.

#31 Ajout décorations "cercle" au Background
  .gitignore
  src/App.vue
  src/assets/circle.svg
  src/components/Background.vue
Labels: UI

#27 Carte transports
  package.json
  public/index.html
  src/App.vue
  src/api.js
  src/components/TransportCard.vue
  src/components/TripTransportCard.vue
Labels: UI, Component

#41 Fix Menu Card style
  src/App.vue
  src/components/MenuCard.vue
Labels: Component

#40 Fix DateHour Header
  src/App.vue
  src/components/DateHourHeader.vue
  src/components/PlanningCard.vue
Labels: bug, Component

#46 Documentation Projet
  CONTRIBUTING.md
  RASPBERRY.md
  README.md
Labels: Hardware

#45 Fix CSS pour format TV
  src/App.vue
  src/components/DateHourHeader.vue
  src/components/MenuCard.vue
  src/components/MeteoCard.vue
  src/components/PlanningCard.vue
  src/components/TransportCard.vue
  src/components/TripTransportCard.vue
  src/views/NextPlannings.vue
  src/views/NextTransports.vue
Labels: Frontend
